messages:
  prefix: '&6Кабинки &7» '
  room_join: '&fИгрок &6%player% &fприсоединился (&6%current_players%&f/&6%need_players%&f)'
  room_quit: '&fИгрок &6%player% &fпокидает комнату.'
  room_busy: '&cЭта PVP комната уже занята, зайдите в другую или подождите конца сражения.'
  you_win: '&aВы победили сражаясь в PVP комнате!'
  you_will_be_teleported_after_win: '&fВы будете телепортированы через &6%sec% &fсек.'
  room_started: '&fPVP комната запущена, сражение начинается!'

rooms:
  room_1:
    world: "spawn"
    region: "room_1"
    end_of_pvp_timer: 30 # Сколько у победителя есть времени на сбор лута если он победил (В секундах)
    need_players: 2 # Количество игроков чтобы PVP комната была запущена.
    outside_teleport_location: # Локация куда будет телепортирован игрок в случае победы/попадения в активную комнату
      x: -11
      y: 82
      z: -53
      yaw: 180
      pitch: 0
    door_locations: # Список координат блоков двери которая закроется в момент начала сражений в комнате.
      from:
        x: -9
        y: 85
        z: -48
      to:
        x: -13
        y: 82
        z: -48

  room_2:
    world: "spawn"
    region: "room_2"
    end_of_pvp_timer: 30 # Сколько у победителя есть времени на сбор лута если он победил (В секундах)
    need_players: 2 # Количество игроков чтобы PVP комната была запущена.
    outside_teleport_location: # Локация куда будет телепортирован игрок в случае победы/попадения в активную комнату
      x: 11
      y: 82
      z: -54
      yaw: 180
      pitch: 0
    door_locations: # Список координат блоков двери которая закроется в момент начала сражений в комнате.
      from:
        x: 13
        y: 85
        z: -48
      to:
        x: 9
        y: 82
        z: -48